### PR TITLE
makes the form look better

### LINKED ISSUE #29: Feat: Improve the Desgin of Form
In the first page of the website the form doesn't look cool so i would suggest to update the UI of whole form.

### PR DESCRIPTION
**Pull request by harshsharma-11**
fix #29

### CODE REVIEW

**Comment by Chirayu31** [comment]
can you provide us the screenshot/video of the changes

**Comment by harshsharma-11** [comment]
https://github.com/gdsc-ipsacademy/resume-builder/assets/138685168/7d13d155-5645-42bb-9a99-b354cec00880

**Comment by zishanverse** [comment]
@harshsharma-11 can you modify CSS: each card of education from when you are adding by "+" , card should be properly viewed with their respective remove button without confusion.

**Comment by harshsharma-11** [comment]
sure but please merge the pr little quickly as hactoberfest end come closer

**Comment by harshsharma-11** [comment]
changes are made in new pr

**Pull request closed without merging**
