### PR TITLE
feat plus

### LINKED ISSUE #34: use of this add buttons
there are buttons like add education these are of no use acc to me 

https://github.com/gdsc-ipsacademy/resume-builder/assets/138685168/ba6d84d5-1b3b-4b29-95f0-e72d144c081f

### PR DESCRIPTION
**Pull request by harshsharma-11**
fixes #34 
fixed this and make the add to plus

### CODE REVIEW

**Comment by harshsharma-11** [comment]
please @JustA3DObject please review the pr and accept it under hactoberfest

**Comment by JustA3DObject** [comment]
> please @JustA3DObject please review the pr and accept it under hactoberfest

I can just review the code. @Chirayu31 will be the one accepting it.

**Comment by harshsharma-11** [comment]
> > please @JustA3DObject please review the pr and accept it under hactoberfest
> 
> I can just review the code. @Chirayu31 will be the one accepting it.

also clarify favicon issue

**Comment by Chirayu31** [comment]
can you show us the screenshots/video of the changes

**Comment by harshsharma-11** [comment]
@Chirayu31 sure

**Comment by harshsharma-11** [comment]
https://github.com/gdsc-ipsacademy/resume-builder/assets/138685168/816d1fac-89d4-4e24-9abd-64c4bb72d28c

**Comment by harshsharma-11** [comment]
@Chirayu31 @JustA3DObject please review the pr

**Comment by zishanverse** [comment]
@harshsharma-11 i reviewed your code, @Chirayu31 sir will accept it soon.

**Comment by harshsharma-11** [comment]
@Chirayu31 @JustA3DOplease review  the pr quickly . please merge these pr 7 days before hactoberfest ends because it takes review time of 7 days after merging

**Pull request closed without merging**
