### PR TITLE
page count added

### LINKED ISSUE #31: [Feat]: Add the number of page opened and total no of pages
Since this is page no 2 so add a tag to display the opened page and total pages in the website

Screenshot (1423)

### PR DESCRIPTION
**Pull request by harshsharma-11**
fixes #31 
i have made changes please check and accept the pr under hactoberfest .And thanks a lot for the issue

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@Chirayu31 @Sky-De please check i have made a pull request

**Comment by Chirayu31** [comment]
looking into it

**Comment by harshsharma-11** [comment]
ya sure

**Comment by Chirayu31** [comment]
provide the screenshots/video of the changes regarding this pr

**Comment by harshsharma-11** [comment]
ok

**Comment by harshsharma-11** [comment]
Screenshot (336)
Screenshot (337)
Screenshot (338)
Screenshot (339)

**Comment by harshsharma-11** [comment]
@Chirayu31 @JustA3DObject please mereg the pr quickly ,respect contributor work too .i contribute in your repository as per hactoberfest .So please merge thewse pr 7 days before hactoberfest ends

**Comment by Chirayu31** [comment]
@harshsharma-11 Thanks for your contribution. However, we won't be merging this PR as the feature isn't required currently and might lead to conflict. Please refrain from spamming repositories; quality contributions are appreciated over quantity. Also, Hacktoberfest isn't synonymous with open source.

**Pull request closed without merging**
