### PR TITLE
Enhancement of buttons

### PR DESCRIPTION
**Pull request by danishagarwal**
Edits - Added className to identify if it is either a submit, add, remove, or download button and added CSS accordingly.

### CODE REVIEW

**Comment by Chirayu31** [comment]
Can you resolve the conflicts?

**Comment by Chirayu31** [comment]
can you provide me the screenshots/videos of the changes please?

**Comment by danishagarwal** [comment]
https://github.com/gdsc-ipsacademy/resume-builder/assets/81150631/b294208d-2fe0-4625-907d-642386e48c9e

**Comment by danishagarwal** [comment]
Same Design on all pages

**Comment by Chirayu31** [comment]
Great work! Just dont change color to blue on hover keep it white only

**Comment by danishagarwal** [comment]
Hi, if you checkout the whole video you'll see add and remove buttons design.

**Comment by danishagarwal** [comment]
@Chirayu31 Add and remove buttons give good hint of Green and Red, blue is okay I removed white looked much better. Hope it;s good in the end ;)

**Comment by Chirayu31** [comment]
@danishagarwal thanks for your contribution! Appreciate it

**Pull request merged**
