### PR TITLE
Feat/look

### LINKED ISSUE #29: Feat: Improve the Desgin of Form
In the first page of the website the form doesn't look cool so i would suggest to update the UI of whole form.

### PR DESCRIPTION
**Pull request by harshsharma-11**
fix #29

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@Ch

https://github.com/gdsc-ipsacademy/resume-builder/assets/138685168/f28abd26-88a0-457c-96f3-bffe703ef19d

irayu31 as suggested change in #36

**Comment by harshsharma-11** [comment]
@Chirayu31 @JustA3DOplease review  the pr quickly . please merge these pr 7 days before hactoberfest ends because it takes review time of 7 days after merging

**Comment by JustA3DObject** [comment]
> @Chirayu31 @JustA3DOplease review  the pr quickly . please merge these pr 7 days before hactoberfest ends because it takes review time of 7 days after merging

Man there's no point in tagging me I can just review your code, which I did a while ago. @Chirayu31 is the owner of the repository and the only one with permission to merge PRs.

(To make this quicker, go to his GitHub profile and spam about your PRs on all his socials. Might actually work)

**Comment by Chirayu31** [comment]
Hi @harshsharma-11,

Thank you for your contributions. However, we believe some improvements are needed to align with our quality standards. We aim to enhance the responsiveness and overall aesthetics of the feature. Your attention to these aspects would be greatly appreciated before we proceed with the merge.

@JustAnother3DObject,
Your suggestion to spam my socials isn't appreciated. Please refrain from directing such toxic behavior.  Thanks.

**Comment by harshsharma-11** [comment]
no i have no further interest regarding contributing to your repo. Never seen such toxic maintainer . @JustA3DObject thanks for your juidance but the @Chirayu31 is not seems like good person to work with, he  so can't continue further

**Pull request closed without merging**
